//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ojk.com/poc4/submit")
package com.ojk.poc4.submit;
