//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ojk.poc4.submit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "POC4ServiceESB", targetNamespace = "http://ojk.com/poc4/submit")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface POC4ServiceESB {


    /**
     * 
     * @param echoParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "echo", targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.EchoResponse")
    @Action(input = "http://ojk.com/poc4/submit/POC4ServiceESB/echoRequest", output = "http://ojk.com/poc4/submit/POC4ServiceESB/echoResponse")
    public String echo(
        @WebParam(name = "echoParam", targetNamespace = "")
        String echoParam);

    /**
     * 
     * @param poc4
     * @return
     *     returns com.ojk.poc4.submit.Poc4Result
     */
    @WebMethod
    @WebResult(name = "POC4Result", targetNamespace = "")
    @RequestWrapper(localName = "submit", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.SubmitResponse")
    @Action(input = "http://ojk.com/poc4/submit/POC4ServiceESB/submitRequest", output = "http://ojk.com/poc4/submit/POC4ServiceESB/submitResponse")
    public Poc4Result submit(
        @WebParam(name = "POC4", targetNamespace = "")
        Poc4 poc4);

    /**
     * 
     * @param poc4
     * @throws SOAPFaultThrower
     */
    @WebMethod
    @RequestWrapper(localName = "submitAsync", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.SubmitAsync")
    @ResponseWrapper(localName = "submitAsyncResponse", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.SubmitAsyncResponse")
    @Action(input = "http://ojk.com/poc4/submit/POC4ServiceESB/submitAsyncRequest", output = "http://ojk.com/poc4/submit/POC4ServiceESB/submitAsyncResponse", fault = {
        @FaultAction(className = SOAPFaultThrower.class, value = "http://ojk.com/poc4/submit/POC4ServiceESB/submitAsync/Fault/SOAPFaultThrower")
    })
    public void submitAsync(
        @WebParam(name = "POC4", targetNamespace = "")
        Poc4 poc4)
        throws SOAPFaultThrower
    ;

    /**
     * 
     * @param poc4
     * @return
     *     returns com.ojk.poc4.submit.Poc4Result
     */
    @WebMethod
    @WebResult(name = "POC4Result", targetNamespace = "")
    @RequestWrapper(localName = "getResult", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.GetResult")
    @ResponseWrapper(localName = "getResultResponse", targetNamespace = "http://ojk.com/poc4/submit", className = "com.ojk.poc4.submit.GetResultResponse")
    @Action(input = "http://ojk.com/poc4/submit/POC4ServiceESB/getResultRequest", output = "http://ojk.com/poc4/submit/POC4ServiceESB/getResultResponse")
    public Poc4Result getResult(
        @WebParam(name = "POC4", targetNamespace = "")
        Poc4 poc4);

}
