//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ojk.poc4.submit;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for poc4 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="poc4">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDTransaksi" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="TanggalTransaksi" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "poc4", propOrder = {
    "idTransaksi",
    "tanggalTransaksi"
})
public class Poc4 {

    @XmlElement(name = "IDTransaksi")
    protected BigDecimal idTransaksi;
    @XmlElement(name = "TanggalTransaksi")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tanggalTransaksi;

    /**
     * Gets the value of the idTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIDTransaksi() {
        return idTransaksi;
    }

    /**
     * Sets the value of the idTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIDTransaksi(BigDecimal value) {
        this.idTransaksi = value;
    }

    /**
     * Gets the value of the tanggalTransaksi property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTanggalTransaksi() {
        return tanggalTransaksi;
    }

    /**
     * Sets the value of the tanggalTransaksi property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTanggalTransaksi(XMLGregorianCalendar value) {
        this.tanggalTransaksi = value;
    }

}
