//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ojk.poc4.submit;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "POC4ServiceESB", targetNamespace = "http://ojk.com/poc4/submit", wsdlLocation = "WEB-INF/wsdl/POC4ServiceESB.wsdl")
public class POC4ServiceESB_Service
    extends Service
{

    private final static URL POC4SERVICEESB_WSDL_LOCATION;
    private final static WebServiceException POC4SERVICEESB_EXCEPTION;
    private final static QName POC4SERVICEESB_QNAME = new QName("http://ojk.com/poc4/submit", "POC4ServiceESB");

    static {
            POC4SERVICEESB_WSDL_LOCATION = com.ojk.poc4.submit.POC4ServiceESB_Service.class.getResource("/WEB-INF/wsdl/POC4ServiceESB.wsdl");
        WebServiceException e = null;
        if (POC4SERVICEESB_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/POC4ServiceESB.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        POC4SERVICEESB_EXCEPTION = e;
    }

    public POC4ServiceESB_Service() {
        super(__getWsdlLocation(), POC4SERVICEESB_QNAME);
    }

    public POC4ServiceESB_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POC4SERVICEESB_QNAME, features);
    }

    public POC4ServiceESB_Service(URL wsdlLocation) {
        super(wsdlLocation, POC4SERVICEESB_QNAME);
    }

    public POC4ServiceESB_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POC4SERVICEESB_QNAME, features);
    }

    public POC4ServiceESB_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public POC4ServiceESB_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns POC4ServiceESB
     */
    @WebEndpoint(name = "POC4ServiceESBPort")
    public POC4ServiceESB getPOC4ServiceESBPort() {
        return super.getPort(new QName("http://ojk.com/poc4/submit", "POC4ServiceESBPort"), POC4ServiceESB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns POC4ServiceESB
     */
    @WebEndpoint(name = "POC4ServiceESBPort")
    public POC4ServiceESB getPOC4ServiceESBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ojk.com/poc4/submit", "POC4ServiceESBPort"), POC4ServiceESB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POC4SERVICEESB_EXCEPTION!= null) {
            throw POC4SERVICEESB_EXCEPTION;
        }
        return POC4SERVICEESB_WSDL_LOCATION;
    }

}
