//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ojk.poc4.submit;

import javax.xml.ws.WebFault;

@WebFault(name = "SOAPFaultThrower", targetNamespace = "http://ojk.com/poc4/submit")
public class SOAPFaultThrower
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultInfoDetail faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SOAPFaultThrower(String message, FaultInfoDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SOAPFaultThrower(String message, FaultInfoDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ojk.poc4.submit.FaultInfoDetail
     */
    public FaultInfoDetail getFaultInfo() {
        return faultInfo;
    }

}
