//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ojk.poc4.submit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for submitResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="submitResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POC4Result" type="{http://ojk.com/poc4/submit}poc4Result" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "submitResponse", propOrder = {
    "poc4Result"
})
public class SubmitResponse {

    @XmlElement(name = "POC4Result")
    protected Poc4Result poc4Result;

    /**
     * Gets the value of the poc4Result property.
     * 
     * @return
     *     possible object is
     *     {@link Poc4Result }
     *     
     */
    public Poc4Result getPOC4Result() {
        return poc4Result;
    }

    /**
     * Sets the value of the poc4Result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Poc4Result }
     *     
     */
    public void setPOC4Result(Poc4Result value) {
        this.poc4Result = value;
    }

}
